version: '3'

services:
  webservice:
    container_name: webservice
    build:
      context: ./webservice
      dockerfile: Dockerfile
    volumes:
      - './webservice:/app'
    ports:
      - 5000:5000
    tty: true
    stdin_open: true
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
